/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author firet
 */
public class Calculadora extends javax.swing.JFrame {

    String valor1;
    String valor2;
    String operador;
    boolean virgula;
    boolean negativo;
   
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_resultado = new javax.swing.JTextField();
        Bot_virgula = new javax.swing.JButton();
        Bot_0 = new javax.swing.JButton();
        Bot_1 = new javax.swing.JButton();
        Bot_2 = new javax.swing.JButton();
        Bot_3 = new javax.swing.JButton();
        Bot_4 = new javax.swing.JButton();
        Bot_5 = new javax.swing.JButton();
        Bot_6 = new javax.swing.JButton();
        Bot_7 = new javax.swing.JButton();
        Bot_8 = new javax.swing.JButton();
        Bot_9 = new javax.swing.JButton();
        Bot_adicao = new javax.swing.JButton();
        Bot_igual = new javax.swing.JButton();
        Bot_subtracao = new javax.swing.JButton();
        Bot_multiplicacao = new javax.swing.JButton();
        Bot_divisao = new javax.swing.JButton();
        Bot_Clear = new javax.swing.JButton();
        Bot_quadrado = new javax.swing.JButton();
        Bot_porcentagem = new javax.swing.JButton();
        Bot_maismenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text_resultado.setEditable(false);
        Text_resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Text_resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Bot_virgula.setText(",");
        Bot_virgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_virgulaActionPerformed(evt);
            }
        });

        Bot_0.setText("0");
        Bot_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_0ActionPerformed(evt);
            }
        });

        Bot_1.setText("1");
        Bot_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_1ActionPerformed(evt);
            }
        });

        Bot_2.setText("2");
        Bot_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_2ActionPerformed(evt);
            }
        });

        Bot_3.setText("3");
        Bot_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_3ActionPerformed(evt);
            }
        });

        Bot_4.setText("4");
        Bot_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_4ActionPerformed(evt);
            }
        });

        Bot_5.setText("5");
        Bot_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_5ActionPerformed(evt);
            }
        });

        Bot_6.setText("6");
        Bot_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_6ActionPerformed(evt);
            }
        });

        Bot_7.setText("7");
        Bot_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_7ActionPerformed(evt);
            }
        });

        Bot_8.setText("8");
        Bot_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_8ActionPerformed(evt);
            }
        });

        Bot_9.setText("9");
        Bot_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_9ActionPerformed(evt);
            }
        });

        Bot_adicao.setText("+");
        Bot_adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_adicaoActionPerformed(evt);
            }
        });

        Bot_igual.setText("=");
        Bot_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_igualActionPerformed(evt);
            }
        });

        Bot_subtracao.setText("-");
        Bot_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_subtracaoActionPerformed(evt);
            }
        });

        Bot_multiplicacao.setText("X");
        Bot_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_multiplicacaoActionPerformed(evt);
            }
        });

        Bot_divisao.setText("/");
        Bot_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_divisaoActionPerformed(evt);
            }
        });

        Bot_Clear.setText("C");
        Bot_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_ClearActionPerformed(evt);
            }
        });

        Bot_quadrado.setText("x²");
        Bot_quadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_quadradoActionPerformed(evt);
            }
        });

        Bot_porcentagem.setText("%");
        Bot_porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_porcentagemActionPerformed(evt);
            }
        });

        Bot_maismenos.setText("+/-");
        Bot_maismenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_maismenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bot_maismenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bot_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Bot_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Bot_0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Bot_virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bot_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bot_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bot_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bot_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bot_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Bot_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bot_quadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Bot_porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bot_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bot_quadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bot_8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bot_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bot_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bot_0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_maismenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot_virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setValor(String num){
        if(operador == null){
            if(valor1 == null){
                valor1 = num;
            }else {
                valor1 += num;
            }
        } else {
            if(valor2 == null){
                valor2 = num;
            } else {
                valor2 += num;
            }
        }
    }
    
    private void setValorNegativo(String num){
        if(operador == null){
            if(valor1 == null){
                valor1 = num;
                negativo = true;
                Text_resultado.setText(valor1);
            }else {
                if (negativo == true){
                    valor1 += num;
                } else if(negativo == false){
                    String x = valor1;
                    valor1 = num;
                    valor1 += x;
                    negativo = true;
                    Text_resultado.setText(valor1);
                }
            }
            }
         else {
            if(valor2 == null){
                valor2 = num;
                negativo = true;
                Text_resultado.setText(valor1 + " " + operador + " " + valor2);
            }else {
                if (negativo == true){
                    valor2 += num;
                } else if(negativo == false){
                    String x = valor2;
                    valor2 = num;
                    valor2 += x;
                    negativo = true;
                    Text_resultado.setText(valor1 + " " + operador + " " + valor2);
                }
        }
        }
    }
    
    private void setValorQuadrado(){
        if(operador == "^"){
            if(valor1 != null){
                Float x = Float.valueOf(valor1);
                Float z = x * x;
                valor1 = String.valueOf(z);
            }
        } else {
            if(valor2 != null){
                Float x = Float.valueOf(valor2);
                Float z = x * x;
                valor2 = String.valueOf(z);
            }
        }
    }
    
    private void checarVazio(){
        if(valor1 == null && valor2 == null && operador == null && negativo == false && !Text_resultado.getText().isEmpty()){
            Text_resultado.setText(null);
        }
    }
    
    private void checar(){
        if(valor1 == null && valor2 == null && operador == null && negativo == false && !Text_resultado.getText().isEmpty()){
            setValor(Text_resultado.getText());
        }
    }
    
    private void Bot_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_subtracaoActionPerformed
        checar();
        operador = "-";
        Text_resultado.setText(Text_resultado.getText() + " - ");
    }//GEN-LAST:event_Bot_subtracaoActionPerformed

    private void Bot_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_divisaoActionPerformed
        checar();
        operador = "/";
        Text_resultado.setText(Text_resultado.getText() + " / ");
    }//GEN-LAST:event_Bot_divisaoActionPerformed

    private void Bot_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_multiplicacaoActionPerformed
        checar();
        operador = "x";
        Text_resultado.setText(Text_resultado.getText() + " x ");
    }//GEN-LAST:event_Bot_multiplicacaoActionPerformed

    private void Bot_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_igualActionPerformed
        Float avalor1 = Float.valueOf(valor1);
        Float avalor2 = Float.valueOf(valor2);
        if(operador == "+"){
            Text_resultado.setText(String.valueOf(avalor1 + avalor2));
        }else{
            if(operador == "-"){
                Text_resultado.setText(String.valueOf(avalor1 - avalor2));
            }
            else {
                if(operador == "x"){
                    Text_resultado.setText(String.valueOf(avalor1 * avalor2));
                }
                else {
                    if(operador == "/"){
                        Text_resultado.setText(String.valueOf(avalor1 / avalor2));
                    }
                    else {
                        if(operador == "%"){
                            Text_resultado.setText(String.valueOf((avalor1 / 100) * avalor2));
                        }
                    }
                }
            }
        }
        valor1 = null;
        valor2 = null;
        operador = null;
        virgula = false;
        negativo = false;
    }//GEN-LAST:event_Bot_igualActionPerformed

    private void Bot_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_0ActionPerformed
        checarVazio();
        setValor("0");
        Text_resultado.setText(Text_resultado.getText() + "0");
    }//GEN-LAST:event_Bot_0ActionPerformed

    private void Bot_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_1ActionPerformed
        checarVazio();
        setValor("1");
        Text_resultado.setText(Text_resultado.getText() + "1");
    }//GEN-LAST:event_Bot_1ActionPerformed

    private void Bot_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_2ActionPerformed
        checarVazio();
        setValor("2");
        Text_resultado.setText(Text_resultado.getText() + "2");
    }//GEN-LAST:event_Bot_2ActionPerformed

    private void Bot_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_3ActionPerformed
        checarVazio();
        setValor("3");
        Text_resultado.setText(Text_resultado.getText() + "3");
    }//GEN-LAST:event_Bot_3ActionPerformed

    private void Bot_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_4ActionPerformed
        checarVazio();
        setValor("4");
        Text_resultado.setText(Text_resultado.getText() + "4");
    }//GEN-LAST:event_Bot_4ActionPerformed

    private void Bot_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_5ActionPerformed
        checarVazio();
        setValor("5");
        Text_resultado.setText(Text_resultado.getText() + "5");
    }//GEN-LAST:event_Bot_5ActionPerformed

    private void Bot_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_6ActionPerformed
        checarVazio();
        setValor("6");
        Text_resultado.setText(Text_resultado.getText() + "6");
    }//GEN-LAST:event_Bot_6ActionPerformed

    private void Bot_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_7ActionPerformed
        checarVazio();
        setValor("7");
        Text_resultado.setText(Text_resultado.getText() + "7");
    }//GEN-LAST:event_Bot_7ActionPerformed

    private void Bot_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_8ActionPerformed
        checarVazio();
        setValor("8");
        Text_resultado.setText(Text_resultado.getText() + "8");
    }//GEN-LAST:event_Bot_8ActionPerformed

    private void Bot_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_9ActionPerformed
        checarVazio();
        setValor("9");
        Text_resultado.setText(Text_resultado.getText() + "9");
    }//GEN-LAST:event_Bot_9ActionPerformed

    private void Bot_adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_adicaoActionPerformed
        checar();
        operador = "+";
        Text_resultado.setText(Text_resultado.getText() + " + ");
    }//GEN-LAST:event_Bot_adicaoActionPerformed

    private void Bot_virgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_virgulaActionPerformed
        checarVazio();
        if(Text_resultado.getText().isEmpty()){
            setValor("0.");
            Text_resultado.setText("0.");
            virgula = true;
        } else if(virgula == false){
            setValor(".");
            Text_resultado.setText(Text_resultado.getText() + ".");
            virgula = true;
        } 
    }//GEN-LAST:event_Bot_virgulaActionPerformed

    private void Bot_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_ClearActionPerformed
        Text_resultado.setText(null);
        valor1 = null;
        valor2 = null;
        operador = null;
        virgula = false;
        negativo = false;
    }//GEN-LAST:event_Bot_ClearActionPerformed

    private void Bot_quadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_quadradoActionPerformed
        checar();
        operador = "^";
        Text_resultado.setText(Text_resultado.getText() + "^(2)");
    }//GEN-LAST:event_Bot_quadradoActionPerformed

    private void Bot_porcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_porcentagemActionPerformed
        checar();
        operador = "%";
        Text_resultado.setText(Text_resultado.getText() + " % ");
    }//GEN-LAST:event_Bot_porcentagemActionPerformed

    private void Bot_maismenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_maismenosActionPerformed
        checarVazio();
        setValorNegativo("-");
        
    }//GEN-LAST:event_Bot_maismenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_0;
    private javax.swing.JButton Bot_1;
    private javax.swing.JButton Bot_2;
    private javax.swing.JButton Bot_3;
    private javax.swing.JButton Bot_4;
    private javax.swing.JButton Bot_5;
    private javax.swing.JButton Bot_6;
    private javax.swing.JButton Bot_7;
    private javax.swing.JButton Bot_8;
    private javax.swing.JButton Bot_9;
    private javax.swing.JButton Bot_Clear;
    private javax.swing.JButton Bot_adicao;
    private javax.swing.JButton Bot_divisao;
    private javax.swing.JButton Bot_igual;
    private javax.swing.JButton Bot_maismenos;
    private javax.swing.JButton Bot_multiplicacao;
    private javax.swing.JButton Bot_porcentagem;
    private javax.swing.JButton Bot_quadrado;
    private javax.swing.JButton Bot_subtracao;
    private javax.swing.JButton Bot_virgula;
    private javax.swing.JTextField Text_resultado;
    // End of variables declaration//GEN-END:variables
}
